### ISSUE TITLE
Suggestion: Possible to .convert everything

### ISSUE THREAD

**Issue by alexwoll** [andersju/nucdawn#1]
I feel a bit constraint with just https://github.com/carturoch/ex_uc#included-units as the convert units.

I would love to be able to convert for example "btc to eur" or "acres to hectares" and the likes.

**Comment by andersju** [comment]
That's not in the pipeline for now but I'll add acres, hectares and a bunch of others! The equivalent of btc -> eur can be had with `.cur btc` (which prints USD and EUR rates). Maybe there's a nice public REST API somewhere that can do all kinds of conversions?

**Comment by alexwoll** [comment]
👍
